Models/Calisan.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebÖdev.Models
{
    public class Calisan
    {
        [Key]
        public int CalisanId { get; set; }

        [Required]
        [DisplayName("Çalışan Adı")]
        public string CalisanAdi { get; set; }
        [DisplayName("Uzmanlık Alanı")]
        public string UzmanlikAlani { get; set; }
        [DisplayName("İş Başı Saati")]
        public TimeSpan? UygunlukBaslangic { get; set; }
        [DisplayName("İş Bitiş Saati")]
        public TimeSpan? UygunlukBitis { get; set; }

         [ForeignKey("Salon")]
        public int SalonId { get; set; }

        // Navigation Property
        public Salonlar Salon { get; set; }

        public ICollection<Randevu> Randevular { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace WebÖdev.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Hizmetler.cs
namespace WebÖdev.Models
{
    public class Hizmetler
    {

        public int HizmetlerId { get; set; }
        public string HizmetName { get; set; }
        public int HizmetSuresi { get; set; }
        public int HizmetFiyat { get; set; }

        public ICollection<Randevu> Randevular { get; set; }
    }
}

Models/Randevu.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebÖdev.Models
{
    public class Randevu
    {
        public int RandevuId { get; set; }


        
        public string MusteriName { get; set; }
        public int CalisanId { get; set; }

        public int  HizmetId { get; set; }

        public DateTime RandevuZamani { get; set; }
        public enum RandevuDurum
        {
            Bekliyor,
            Onaylandi,
            IptalEdildi
        }
        public RandevuDurum RandevuDurumu { get; set; }


        // Navigation Properties
        [ForeignKey("CalisanId")]
        public Calisan Calisan { get; set; }    // Çalışanla ilişki

        [ForeignKey("HizmetId")]
        public Hizmetler Hizmet { get; set; }      // Hizmetle ilişki

    }
}

Models/Salonlar.cs
namespace WebÖdev.Models
{
    public class Salonlar
    {
        public int Id { get; set; }
        public string SalonAdi { get; set; }
        public string CalismaSaatleri {  get; set; }   
        public string SalonAdres {  get; set; }

        public ICollection<Calisan> Calisanlar { get; set; }

    }
}

Controllers/CalisanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebÖdev.Models;
using WebÖdev.Utility;

namespace WebÖdev.Controllers
{
    public class CalisanController : Controller
    {
        private readonly UygulamaDbContext _uygulamaDbContext;

        public CalisanController(UygulamaDbContext context)
        {
            _uygulamaDbContext = context;
        }
        public IActionResult Index()
        {
            List<Calisan> objCalisanList = _uygulamaDbContext.Calisanlar.ToList();
            return View(objCalisanList);  
        }
       

        public IActionResult CalisanEkle() 
        {
            

            return View(); 
        
        }
        [HttpPost] 
        public IActionResult CalisanEkle(Calisan calisan)
        {

            _uygulamaDbContext.Calisanlar.Add(calisan);
            _uygulamaDbContext.SaveChanges();

            return RedirectToAction("Index","Calisan");
        }

    }
}

Controllers/HizmetlerController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebÖdev.Controllers
{
    public class HizmetlerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebÖdev.Models;

namespace WebÖdev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calisan/CalisanEkle.cshtml
@model Calisan



<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-bg-danger-primary">Çalışan Ekle</h2>
            <hr />
        </div>

        <!-- Çalışan Adı -->
        <div class="mb-3">
            <label asp-for="CalisanAdi"></label>
            <input asp-for="CalisanAdi" class="form-control" name="CalisanAdi" />
        </div>

        <!-- Uzmanlık Alanları -->
        <div class="mb-3">
            <label asp-for="UzmanlikAlani"></label>
            <input asp-for="UzmanlikAlani" class="form-control" name="UzmanlikAlani" />
        </div>

        <!-- İşe Başlama Saati -->
        <div class="mb-3">
            <label asp-for="UygunlukBaslangic"></label>
            <input type="time" asp-for="UygunlukBaslangic" class="form-control" name="UygunlukBaslangic" />
        </div>

        <!-- İşe Bitiş Saati -->
        <div class="mb-3">
            <label asp-for="UygunlukBitis"></label>
            <input  type="time" asp-for="UygunlukBitis" class="form-control" name="UygunlukBitis" />
        </div>

        <!-- SalonId (Gizli) -->
        <input asp-for="SalonId" type="hidden" name="SalonId" value="1" />
        <!-- Submit Butonu -->
        <div class="text-end">
            <button type="submit" class="btn btn-primary">Çalışan Ekle</button>
            <a asp-controller="Calisan" asp-action="Index" class="btn btn-primary">Geri Dön</a>
            
        </div>
    </div>

</form>

Views/Calisan/Index.cshtml
@model List<Calisan> 


<div class="container mt-5">
    <div class=" row pt-3 pb-4">

        <div>
            <h2>Çalışanlar</h2>
        </div>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>

                <th>Çalışan Id</th>
				<th>Adı</th>
				<th>Uzmanlık Alanları</th>
				<th>İş Başı Saati</th>
                <th>İş Bitiriş Saati</th>
                <th>Çalıştığı Salon Id</th>

                
				

                
            </tr>
        </thead>
        <tbody>
            @foreach (var calisan in Model)
            {


                <tr>
                    <td>@calisan.CalisanId</td>
                    <td>@calisan.CalisanAdi</td>
                    <td>@calisan.UzmanlikAlani</td>
                    <td>@calisan.UygunlukBaslangic</td>
                    <td>@calisan.UygunlukBitis</td>
                    <td>@calisan.SalonId</td>
				</tr>
			}





		</tbody>
    </table>

        <div class="row pt-3 pb-2">
             <div>
                 <a asp-controller="Calisan" asp-action="CalisanEkle" class="btn btn-lg btn-primary" type="button">
                    Yeni Çalışan Oluştur
                 </a>
             </div>    
        
        </div>


    </div>
    

Views/Home/Index.cshtml
<div class="container mt-5">
    <h1 class="text-center">Kuaför Bünyamin'e Hoşgeldiniz</h1>

    <div class="row">
        <div class="col-md-6">
            <h2>Hakkımızda:</h2>
            <p><strong>Salon Adı:</strong> Kuaför Bünyamin</p>
            <p><strong>Çalışma Saatleri:</strong> 09:00 - 19:00</p>
            <p><strong>Adres:</strong> İstiklal Cd. No: 10, İstanbul</p>
        </div>

       

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kuaför Randevu Sistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap (2).css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebÖdev.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kuaför Randevu Sistemi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Calisan" asp-action="Index">Çalışanlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Hizmetler" asp-action="Index">Sunduğumuz Hizmetler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebÖdev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>